# Site Settings
title: My Resume
url: 'http://kenny.pittcrew.org'
baseurl: '' #change it according to your repository name
about: false # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Alan Doe
tagline: Senior Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Talented senior developer, architect, and technical leader with over 25 years of progressive experience
across the entire product development cycle. Recognized as an expert in analysis, architecture, design, and
implementation of n-tier Web applications, Windows GUI applications, and Windows services. Reputation for delivering
innovative solutions for the most complex and high profile projects. Proven ability to learn and become productive
quickly with new technologies and environments. Outstanding technical expertise and industry knowledge in enterprise
application security and retail technology solutions. Excellent communication and presentation skills, including
project presentations, training sessions, and technical documentation.'

#sidebar links
email: hello@webjeda.com
phone: 012 345 6789
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
